# Generated by Django 5.1.6 on 2025-05-20 07:51

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('computer_science', 'Computer Science Department'), ('networks', 'Networks Department'), ('information_systems', 'Information Systems'), ('information_technology', 'Information Technology')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(choices=[('computer_science', 'Bachelor of Science in Computer Science'), ('software_engineering', 'Bachelor of Science in Software Engineering'), ('BIST', 'Bachelor Information Systems and Technology'), ('BLIS', 'Bachelor of Library and Information Sciences')], max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('registrar', 'Registrar')], default='student', max_length=20)),
                ('staff_id_or_student_no', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(choices=[('computer_science', 'Bachelor of Science in Computer Science'), ('software_engineering', 'Bachelor of Science in Software Engineering'), ('BIST', 'Bachelor Information Systems and Technology'), ('BLIS', 'Bachelor of Library and Information Sciences')], max_length=200)),
                ('course_name', models.CharField(max_length=150)),
                ('course_code', models.CharField(max_length=50)),
                ('year_of_study', models.CharField(choices=[('year_1', 'Year 1'), ('year_2', 'Year 2'), ('year_3', 'Year 3'), ('year_4', 'Year 4'), ('year_5', 'Year 5')], help_text='your year of study', max_length=50)),
                ('category', models.CharField(choices=[('Missing_Marks', 'Missing marks'), ('Wrong_grading', 'wrong grading'), ('wrong_marks', 'wrong marks'), ('other', 'other')], max_length=100)),
                ('description', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='issue_pics')),
                ('department', models.CharField(choices=[('computer_science', 'Computer Science Department'), ('networks', 'Networks Department'), ('information_systems', 'Information Systems'), ('information_technology', 'Information Technology')], max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('lecturer', models.ForeignKey(blank=True, limit_choices_to={'role': 'lecturer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_issues', to=settings.AUTH_USER_MODEL)),
                ('registrar', models.ForeignKey(limit_choices_to={'role': 'registrar'}, on_delete=django.db.models.deletion.CASCADE, related_name='registra_issues', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_code_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
