# Generated by Django 5.1.6 on 2025-04-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='couse_name',
            new_name='course_name',
        ),
    ]
