# Generated by Django 5.1.6 on 2025-03-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staff_id_or_student_no',
            field=models.IntegerField(default=0),
        ),
    ]
