# Generated by Django 5.1.6 on 2025-03-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='issue_pics'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='course_code',
            field=models.CharField(help_text='course code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='couse_name',
            field=models.CharField(help_text='course name', max_length=150, null=True),
        ),
    ]
