# Generated by Django 5.1.6 on 2025-02-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'permissions': [('report_issue', 'can report an issue'), ('assign_issue', 'can assign issue')]},
        ),
    ]
