# Generated by Django 5.1.6 on 2025-03-28 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='lecturer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Lecturer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_issues', to=settings.AUTH_USER_MODEL),
        ),
    ]
