# Generated by Django 5.1.5 on 2025-02-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('computer_science', 'Computer Science Department'), ('networks', 'Networks Department'), ('information_systems', 'Information Systems'), ('information_technology', 'Information Technology')], max_length=100),
        ),
    ]
