# Generated by Django 5.1.5 on 2025-02-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_issue_assigned_to_issue_course_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='title',
            new_name='category',
        ),
    ]
